"""
Standard Occupational Classification (SOC) Occupations
=======================================================

Comprehensive list of SOC occupation codes used by BLS for OES data.
Source: U.S. Bureau of Labor Statistics Standard Occupational Classification System

The SOC system classifies workers into occupational categories for statistical purposes.
- 2-digit: Major groups (e.g., 15 = Computer and Mathematical Occupations)
- 3-digit: Minor groups
- 5-digit: Broad occupations
- 6-digit: Detailed occupations (what BLS uses for OES)

This list includes ~450 of the most common detailed occupations relevant to
workforce development and career technical education programs.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel


class SOCOccupation(BaseModel):
    """SOC occupation with code and title."""
    code: str  # 6-digit code without hyphen (e.g., "291141")
    title: str  # Occupation title
    major_group: str  # 2-digit major group code
    major_group_title: str  # Major group name


# Major occupation groups
MAJOR_GROUPS = {
    "11": "Management Occupations",
    "13": "Business and Financial Operations Occupations",
    "15": "Computer and Mathematical Occupations",
    "17": "Architecture and Engineering Occupations",
    "19": "Life, Physical, and Social Science Occupations",
    "21": "Community and Social Service Occupations",
    "23": "Legal Occupations",
    "25": "Educational Instruction and Library Occupations",
    "27": "Arts, Design, Entertainment, Sports, and Media Occupations",
    "29": "Healthcare Practitioners and Technical Occupations",
    "31": "Healthcare Support Occupations",
    "33": "Protective Service Occupations",
    "35": "Food Preparation and Serving Related Occupations",
    "37": "Building and Grounds Cleaning and Maintenance Occupations",
    "39": "Personal Care and Service Occupations",
    "41": "Sales and Related Occupations",
    "43": "Office and Administrative Support Occupations",
    "45": "Farming, Fishing, and Forestry Occupations",
    "47": "Construction and Extraction Occupations",
    "49": "Installation, Maintenance, and Repair Occupations",
    "51": "Production Occupations",
    "53": "Transportation and Material Moving Occupations",
}

# Comprehensive list of detailed occupations (6-digit SOC codes)
# Organized by major group for easier maintenance
SOC_OCCUPATIONS: List[Dict[str, str]] = [
    # 11 - Management Occupations
    {"code": "111011", "title": "Chief Executives"},
    {"code": "111021", "title": "General and Operations Managers"},
    {"code": "111031", "title": "Legislators"},
    {"code": "112011", "title": "Advertising and Promotions Managers"},
    {"code": "112021", "title": "Marketing Managers"},
    {"code": "112022", "title": "Sales Managers"},
    {"code": "112031", "title": "Public Relations and Fundraising Managers"},
    {"code": "113011", "title": "Administrative Services Managers"},
    {"code": "113012", "title": "Facilities Managers"},
    {"code": "113021", "title": "Computer and Information Systems Managers"},
    {"code": "113031", "title": "Financial Managers"},
    {"code": "113051", "title": "Industrial Production Managers"},
    {"code": "113061", "title": "Purchasing Managers"},
    {"code": "113071", "title": "Transportation, Storage, and Distribution Managers"},
    {"code": "113111", "title": "Compensation and Benefits Managers"},
    {"code": "113121", "title": "Human Resources Managers"},
    {"code": "113131", "title": "Training and Development Managers"},
    {"code": "119013", "title": "Farmers, Ranchers, and Other Agricultural Managers"},
    {"code": "119021", "title": "Construction Managers"},
    {"code": "119030", "title": "Education and Childcare Administrators"},
    {"code": "119041", "title": "Architectural and Engineering Managers"},
    {"code": "119051", "title": "Food Service Managers"},
    {"code": "119071", "title": "Gambling Managers"},
    {"code": "119081", "title": "Lodging Managers"},
    {"code": "119111", "title": "Medical and Health Services Managers"},
    {"code": "119121", "title": "Natural Sciences Managers"},
    {"code": "119141", "title": "Property, Real Estate, and Community Association Managers"},
    {"code": "119151", "title": "Social and Community Service Managers"},
    {"code": "119161", "title": "Emergency Management Directors"},
    {"code": "119199", "title": "Managers, All Other"},

    # 13 - Business and Financial Operations Occupations
    {"code": "131011", "title": "Agents and Business Managers of Artists, Performers, and Athletes"},
    {"code": "131021", "title": "Buyers and Purchasing Agents, Farm Products"},
    {"code": "131022", "title": "Wholesale and Retail Buyers, Except Farm Products"},
    {"code": "131023", "title": "Purchasing Agents, Except Wholesale, Retail, and Farm Products"},
    {"code": "131031", "title": "Claims Adjusters, Examiners, and Investigators"},
    {"code": "131032", "title": "Insurance Appraisers, Auto Damage"},
    {"code": "131041", "title": "Compliance Officers"},
    {"code": "131051", "title": "Cost Estimators"},
    {"code": "131071", "title": "Human Resources Specialists"},
    {"code": "131074", "title": "Farm Labor Contractors"},
    {"code": "131075", "title": "Labor Relations Specialists"},
    {"code": "131081", "title": "Logisticians"},
    {"code": "131082", "title": "Project Management Specialists"},
    {"code": "131111", "title": "Management Analysts"},
    {"code": "131121", "title": "Meeting, Convention, and Event Planners"},
    {"code": "131131", "title": "Fundraisers"},
    {"code": "131141", "title": "Compensation, Benefits, and Job Analysis Specialists"},
    {"code": "131151", "title": "Training and Development Specialists"},
    {"code": "131161", "title": "Market Research Analysts and Marketing Specialists"},
    {"code": "131199", "title": "Business Operations Specialists, All Other"},
    {"code": "132011", "title": "Accountants and Auditors"},
    {"code": "132020", "title": "Property Appraisers and Assessors"},
    {"code": "132031", "title": "Budget Analysts"},
    {"code": "132041", "title": "Credit Analysts"},
    {"code": "132051", "title": "Financial and Investment Analysts"},
    {"code": "132052", "title": "Personal Financial Advisors"},
    {"code": "132053", "title": "Insurance Underwriters"},
    {"code": "132061", "title": "Financial Examiners"},
    {"code": "132072", "title": "Loan Officers"},
    {"code": "132081", "title": "Tax Examiners and Collectors, and Revenue Agents"},
    {"code": "132082", "title": "Tax Preparers"},
    {"code": "132099", "title": "Financial Specialists, All Other"},

    # 15 - Computer and Mathematical Occupations
    {"code": "151211", "title": "Computer Systems Analysts"},
    {"code": "151212", "title": "Information Security Analysts"},
    {"code": "151221", "title": "Computer and Information Research Scientists"},
    {"code": "151231", "title": "Computer Network Support Specialists"},
    {"code": "151232", "title": "Computer User Support Specialists"},
    {"code": "151241", "title": "Computer Network Architects"},
    {"code": "151244", "title": "Network and Computer Systems Administrators"},
    {"code": "151245", "title": "Database Administrators and Architects"},
    {"code": "151251", "title": "Computer Programmers"},
    {"code": "151252", "title": "Software Developers"},
    {"code": "151253", "title": "Software Quality Assurance Analysts and Testers"},
    {"code": "151254", "title": "Web Developers"},
    {"code": "151255", "title": "Web and Digital Interface Designers"},
    {"code": "151299", "title": "Computer Occupations, All Other"},
    {"code": "152011", "title": "Actuaries"},
    {"code": "152021", "title": "Mathematicians"},
    {"code": "152031", "title": "Operations Research Analysts"},
    {"code": "152041", "title": "Statisticians"},
    {"code": "152051", "title": "Data Scientists"},
    {"code": "152099", "title": "Mathematical Science Occupations, All Other"},

    # 17 - Architecture and Engineering Occupations
    {"code": "171011", "title": "Architects, Except Landscape and Naval"},
    {"code": "171012", "title": "Landscape Architects"},
    {"code": "171021", "title": "Cartographers and Photogrammetrists"},
    {"code": "171022", "title": "Surveyors"},
    {"code": "172011", "title": "Aerospace Engineers"},
    {"code": "172021", "title": "Agricultural Engineers"},
    {"code": "172031", "title": "Bioengineers and Biomedical Engineers"},
    {"code": "172041", "title": "Chemical Engineers"},
    {"code": "172051", "title": "Civil Engineers"},
    {"code": "172061", "title": "Computer Hardware Engineers"},
    {"code": "172071", "title": "Electrical Engineers"},
    {"code": "172072", "title": "Electronics Engineers, Except Computer"},
    {"code": "172081", "title": "Environmental Engineers"},
    {"code": "172111", "title": "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors"},
    {"code": "172112", "title": "Industrial Engineers"},
    {"code": "172121", "title": "Marine Engineers and Naval Architects"},
    {"code": "172131", "title": "Materials Engineers"},
    {"code": "172141", "title": "Mechanical Engineers"},
    {"code": "172151", "title": "Mining and Geological Engineers, Including Mining Safety Engineers"},
    {"code": "172161", "title": "Nuclear Engineers"},
    {"code": "172171", "title": "Petroleum Engineers"},
    {"code": "172199", "title": "Engineers, All Other"},
    {"code": "173011", "title": "Architectural and Civil Drafters"},
    {"code": "173012", "title": "Electrical and Electronics Drafters"},
    {"code": "173013", "title": "Mechanical Drafters"},
    {"code": "173019", "title": "Drafters, All Other"},
    {"code": "173021", "title": "Aerospace Engineering and Operations Technologists and Technicians"},
    {"code": "173022", "title": "Civil Engineering Technologists and Technicians"},
    {"code": "173023", "title": "Electrical and Electronic Engineering Technologists and Technicians"},
    {"code": "173024", "title": "Electro-Mechanical and Mechatronics Technologists and Technicians"},
    {"code": "173025", "title": "Environmental Engineering Technologists and Technicians"},
    {"code": "173026", "title": "Industrial Engineering Technologists and Technicians"},
    {"code": "173027", "title": "Mechanical Engineering Technologists and Technicians"},
    {"code": "173028", "title": "Calibration Technologists and Technicians"},
    {"code": "173029", "title": "Engineering Technologists and Technicians, Except Drafters, All Other"},
    {"code": "173031", "title": "Surveying and Mapping Technicians"},

    # 19 - Life, Physical, and Social Science Occupations
    {"code": "191010", "title": "Agricultural and Food Scientists"},
    {"code": "191021", "title": "Biochemists and Biophysicists"},
    {"code": "191022", "title": "Microbiologists"},
    {"code": "191023", "title": "Zoologists and Wildlife Biologists"},
    {"code": "191029", "title": "Biological Scientists, All Other"},
    {"code": "191031", "title": "Conservation Scientists"},
    {"code": "191032", "title": "Foresters"},
    {"code": "191041", "title": "Epidemiologists"},
    {"code": "191042", "title": "Medical Scientists, Except Epidemiologists"},
    {"code": "192011", "title": "Astronomers"},
    {"code": "192012", "title": "Physicists"},
    {"code": "192021", "title": "Atmospheric and Space Scientists"},
    {"code": "192031", "title": "Chemists"},
    {"code": "192032", "title": "Materials Scientists"},
    {"code": "192041", "title": "Environmental Scientists and Specialists, Including Health"},
    {"code": "192042", "title": "Geoscientists, Except Hydrologists and Geographers"},
    {"code": "192043", "title": "Hydrologists"},
    {"code": "193011", "title": "Economists"},
    {"code": "193022", "title": "Survey Researchers"},
    {"code": "193033", "title": "Clinical and Counseling Psychologists"},
    {"code": "193034", "title": "School Psychologists"},
    {"code": "193039", "title": "Psychologists, All Other"},
    {"code": "193041", "title": "Sociologists"},
    {"code": "193051", "title": "Urban and Regional Planners"},
    {"code": "193091", "title": "Anthropologists and Archeologists"},
    {"code": "193092", "title": "Geographers"},
    {"code": "193093", "title": "Historians"},
    {"code": "193094", "title": "Political Scientists"},
    {"code": "193099", "title": "Social Scientists and Related Workers, All Other"},
    {"code": "194011", "title": "Agricultural and Food Science Technicians"},
    {"code": "194021", "title": "Biological Technicians"},
    {"code": "194031", "title": "Chemical Technicians"},
    {"code": "194042", "title": "Environmental Science and Protection Technicians, Including Health"},
    {"code": "194051", "title": "Nuclear Technicians"},
    {"code": "194061", "title": "Social Science Research Assistants"},
    {"code": "194071", "title": "Forest and Conservation Technicians"},
    {"code": "194099", "title": "Life, Physical, and Social Science Technicians, All Other"},

    # 21 - Community and Social Service Occupations
    {"code": "211011", "title": "Substance Abuse and Behavioral Disorder Counselors"},
    {"code": "211012", "title": "Educational, Guidance, and Career Counselors and Advisors"},
    {"code": "211013", "title": "Marriage and Family Therapists"},
    {"code": "211014", "title": "Mental Health Counselors"},
    {"code": "211015", "title": "Rehabilitation Counselors"},
    {"code": "211019", "title": "Counselors, All Other"},
    {"code": "211021", "title": "Child, Family, and School Social Workers"},
    {"code": "211022", "title": "Healthcare Social Workers"},
    {"code": "211023", "title": "Mental Health and Substance Abuse Social Workers"},
    {"code": "211029", "title": "Social Workers, All Other"},
    {"code": "211091", "title": "Health Education Specialists"},
    {"code": "211092", "title": "Probation Officers and Correctional Treatment Specialists"},
    {"code": "211093", "title": "Social and Human Service Assistants"},
    {"code": "211094", "title": "Community Health Workers"},
    {"code": "212011", "title": "Clergy"},
    {"code": "212021", "title": "Directors, Religious Activities and Education"},
    {"code": "212099", "title": "Religious Workers, All Other"},

    # 23 - Legal Occupations
    {"code": "231011", "title": "Lawyers"},
    {"code": "231012", "title": "Judicial Law Clerks"},
    {"code": "231021", "title": "Administrative Law Judges, Adjudicators, and Hearing Officers"},
    {"code": "231022", "title": "Arbitrators, Mediators, and Conciliators"},
    {"code": "231023", "title": "Judges, Magistrate Judges, and Magistrates"},
    {"code": "232011", "title": "Paralegals and Legal Assistants"},
    {"code": "232093", "title": "Title Examiners, Abstractors, and Searchers"},
    {"code": "232099", "title": "Legal Support Workers, All Other"},

    # 25 - Educational Instruction and Library Occupations
    {"code": "251000", "title": "Postsecondary Teachers"},
    {"code": "251011", "title": "Business Teachers, Postsecondary"},
    {"code": "251021", "title": "Computer Science Teachers, Postsecondary"},
    {"code": "251022", "title": "Mathematical Science Teachers, Postsecondary"},
    {"code": "251031", "title": "Architecture Teachers, Postsecondary"},
    {"code": "251032", "title": "Engineering Teachers, Postsecondary"},
    {"code": "251041", "title": "Agricultural Sciences Teachers, Postsecondary"},
    {"code": "251042", "title": "Biological Science Teachers, Postsecondary"},
    {"code": "251043", "title": "Forestry and Conservation Science Teachers, Postsecondary"},
    {"code": "251051", "title": "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary"},
    {"code": "251052", "title": "Chemistry Teachers, Postsecondary"},
    {"code": "251053", "title": "Environmental Science Teachers, Postsecondary"},
    {"code": "251054", "title": "Physics Teachers, Postsecondary"},
    {"code": "251061", "title": "Anthropology and Archeology Teachers, Postsecondary"},
    {"code": "251062", "title": "Area, Ethnic, and Cultural Studies Teachers, Postsecondary"},
    {"code": "251063", "title": "Economics Teachers, Postsecondary"},
    {"code": "251064", "title": "Geography Teachers, Postsecondary"},
    {"code": "251065", "title": "Political Science Teachers, Postsecondary"},
    {"code": "251066", "title": "Psychology Teachers, Postsecondary"},
    {"code": "251067", "title": "Sociology Teachers, Postsecondary"},
    {"code": "251069", "title": "Social Sciences Teachers, Postsecondary, All Other"},
    {"code": "251071", "title": "Health Specialties Teachers, Postsecondary"},
    {"code": "251072", "title": "Nursing Instructors and Teachers, Postsecondary"},
    {"code": "251081", "title": "Education Teachers, Postsecondary"},
    {"code": "251082", "title": "Library Science Teachers, Postsecondary"},
    {"code": "251111", "title": "Criminal Justice and Law Enforcement Teachers, Postsecondary"},
    {"code": "251112", "title": "Law Teachers, Postsecondary"},
    {"code": "251113", "title": "Social Work Teachers, Postsecondary"},
    {"code": "251121", "title": "Art, Drama, and Music Teachers, Postsecondary"},
    {"code": "251122", "title": "Communications Teachers, Postsecondary"},
    {"code": "251123", "title": "English Language and Literature Teachers, Postsecondary"},
    {"code": "251124", "title": "Foreign Language and Literature Teachers, Postsecondary"},
    {"code": "251125", "title": "History Teachers, Postsecondary"},
    {"code": "251126", "title": "Philosophy and Religion Teachers, Postsecondary"},
    {"code": "251191", "title": "Graduate Teaching Assistants"},
    {"code": "251192", "title": "Home Economics Teachers, Postsecondary"},
    {"code": "251193", "title": "Recreation and Fitness Studies Teachers, Postsecondary"},
    {"code": "251194", "title": "Career/Technical Education Teachers, Postsecondary"},
    {"code": "251199", "title": "Postsecondary Teachers, All Other"},
    {"code": "252011", "title": "Preschool Teachers, Except Special Education"},
    {"code": "252012", "title": "Kindergarten Teachers, Except Special Education"},
    {"code": "252021", "title": "Elementary School Teachers, Except Special Education"},
    {"code": "252022", "title": "Middle School Teachers, Except Special and Career/Technical Education"},
    {"code": "252023", "title": "Career/Technical Education Teachers, Middle School"},
    {"code": "252031", "title": "Secondary School Teachers, Except Special and Career/Technical Education"},
    {"code": "252032", "title": "Career/Technical Education Teachers, Secondary School"},
    {"code": "252050", "title": "Special Education Teachers"},
    {"code": "253011", "title": "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors"},
    {"code": "253021", "title": "Self-Enrichment Teachers"},
    {"code": "253031", "title": "Substitute Teachers, Short-Term"},
    {"code": "253041", "title": "Tutors"},
    {"code": "253099", "title": "Teachers and Instructors, All Other"},
    {"code": "254012", "title": "Curators"},
    {"code": "254013", "title": "Museum Technicians and Conservators"},
    {"code": "254021", "title": "Librarians and Media Collections Specialists"},
    {"code": "254022", "title": "Library Technicians"},
    {"code": "254031", "title": "Library Assistants, Clerical"},
    {"code": "259011", "title": "Audio-Visual and Multimedia Collections Specialists"},
    {"code": "259031", "title": "Instructional Coordinators"},
    {"code": "259041", "title": "Teacher Assistants"},
    {"code": "259099", "title": "Educational Instruction and Library Workers, All Other"},

    # 27 - Arts, Design, Entertainment, Sports, and Media Occupations
    {"code": "271011", "title": "Art Directors"},
    {"code": "271012", "title": "Craft Artists"},
    {"code": "271013", "title": "Fine Artists, Including Painters, Sculptors, and Illustrators"},
    {"code": "271014", "title": "Special Effects Artists and Animators"},
    {"code": "271019", "title": "Artists and Related Workers, All Other"},
    {"code": "271021", "title": "Commercial and Industrial Designers"},
    {"code": "271022", "title": "Fashion Designers"},
    {"code": "271023", "title": "Floral Designers"},
    {"code": "271024", "title": "Graphic Designers"},
    {"code": "271025", "title": "Interior Designers"},
    {"code": "271026", "title": "Merchandise Displayers and Window Trimmers"},
    {"code": "271027", "title": "Set and Exhibit Designers"},
    {"code": "271029", "title": "Designers, All Other"},
    {"code": "272011", "title": "Actors"},
    {"code": "272012", "title": "Producers and Directors"},
    {"code": "272021", "title": "Athletes and Sports Competitors"},
    {"code": "272022", "title": "Coaches and Scouts"},
    {"code": "272023", "title": "Umpires, Referees, and Other Sports Officials"},
    {"code": "272031", "title": "Dancers"},
    {"code": "272032", "title": "Choreographers"},
    {"code": "272041", "title": "Music Directors and Composers"},
    {"code": "272042", "title": "Musicians and Singers"},
    {"code": "272091", "title": "Disc Jockeys, Except Radio"},
    {"code": "272099", "title": "Entertainers and Performers, Sports and Related Workers, All Other"},
    {"code": "273011", "title": "Broadcast Announcers and Radio Disc Jockeys"},
    {"code": "273023", "title": "News Analysts, Reporters, and Journalists"},
    {"code": "273031", "title": "Public Relations Specialists"},
    {"code": "273041", "title": "Editors"},
    {"code": "273042", "title": "Technical Writers"},
    {"code": "273043", "title": "Writers and Authors"},
    {"code": "273091", "title": "Interpreters and Translators"},
    {"code": "273092", "title": "Court Reporters and Simultaneous Captioners"},
    {"code": "273099", "title": "Media and Communication Workers, All Other"},
    {"code": "274011", "title": "Audio and Video Technicians"},
    {"code": "274012", "title": "Broadcast Technicians"},
    {"code": "274014", "title": "Sound Engineering Technicians"},
    {"code": "274015", "title": "Lighting Technicians"},
    {"code": "274021", "title": "Photographers"},
    {"code": "274031", "title": "Camera Operators, Television, Video, and Film"},
    {"code": "274032", "title": "Film and Video Editors"},
    {"code": "274099", "title": "Media and Communication Equipment Workers, All Other"},

    # 29 - Healthcare Practitioners and Technical Occupations
    {"code": "291011", "title": "Chiropractors"},
    {"code": "291021", "title": "Dentists, General"},
    {"code": "291022", "title": "Oral and Maxillofacial Surgeons"},
    {"code": "291023", "title": "Orthodontists"},
    {"code": "291024", "title": "Prosthodontists"},
    {"code": "291029", "title": "Dentists, All Other Specialists"},
    {"code": "291031", "title": "Dietitians and Nutritionists"},
    {"code": "291041", "title": "Optometrists"},
    {"code": "291051", "title": "Pharmacists"},
    {"code": "291071", "title": "Physician Assistants"},
    {"code": "291081", "title": "Podiatrists"},
    {"code": "291122", "title": "Occupational Therapists"},
    {"code": "291123", "title": "Physical Therapists"},
    {"code": "291124", "title": "Radiation Therapists"},
    {"code": "291125", "title": "Recreational Therapists"},
    {"code": "291126", "title": "Respiratory Therapists"},
    {"code": "291127", "title": "Speech-Language Pathologists"},
    {"code": "291128", "title": "Exercise Physiologists"},
    {"code": "291129", "title": "Therapists, All Other"},
    {"code": "291131", "title": "Veterinarians"},
    {"code": "291141", "title": "Registered Nurses"},
    {"code": "291151", "title": "Nurse Anesthetists"},
    {"code": "291161", "title": "Nurse Midwives"},
    {"code": "291171", "title": "Nurse Practitioners"},
    {"code": "291181", "title": "Audiologists"},
    {"code": "291211", "title": "Anesthesiologists"},
    {"code": "291212", "title": "Cardiologists"},
    {"code": "291213", "title": "Dermatologists"},
    {"code": "291214", "title": "Emergency Medicine Physicians"},
    {"code": "291215", "title": "Family Medicine Physicians"},
    {"code": "291216", "title": "General Internal Medicine Physicians"},
    {"code": "291217", "title": "Neurologists"},
    {"code": "291218", "title": "Obstetricians and Gynecologists"},
    {"code": "291221", "title": "Pediatricians, General"},
    {"code": "291222", "title": "Physicians, Pathologists"},
    {"code": "291223", "title": "Psychiatrists"},
    {"code": "291224", "title": "Radiologists"},
    {"code": "291229", "title": "Physicians, All Other"},
    {"code": "291241", "title": "Ophthalmologists, Except Pediatric"},
    {"code": "291242", "title": "Orthopedic Surgeons, Except Pediatric"},
    {"code": "291243", "title": "Pediatric Surgeons"},
    {"code": "291249", "title": "Surgeons, All Other"},
    {"code": "291291", "title": "Acupuncturists"},
    {"code": "291292", "title": "Dental Hygienists"},
    {"code": "291299", "title": "Healthcare Diagnosing or Treating Practitioners, All Other"},
    {"code": "292010", "title": "Clinical Laboratory Technologists and Technicians"},
    {"code": "292021", "title": "Dental Hygienists"},
    {"code": "292031", "title": "Cardiovascular Technologists and Technicians"},
    {"code": "292032", "title": "Diagnostic Medical Sonographers"},
    {"code": "292033", "title": "Nuclear Medicine Technologists"},
    {"code": "292034", "title": "Radiologic Technologists and Technicians"},
    {"code": "292035", "title": "Magnetic Resonance Imaging Technologists"},
    {"code": "292042", "title": "Emergency Medical Technicians"},
    {"code": "292043", "title": "Paramedics"},
    {"code": "292051", "title": "Dietetic Technicians"},
    {"code": "292052", "title": "Pharmacy Technicians"},
    {"code": "292053", "title": "Psychiatric Technicians"},
    {"code": "292055", "title": "Surgical Technologists"},
    {"code": "292056", "title": "Veterinary Technologists and Technicians"},
    {"code": "292057", "title": "Ophthalmic Medical Technicians"},
    {"code": "292061", "title": "Licensed Practical and Licensed Vocational Nurses"},
    {"code": "292072", "title": "Medical Records Specialists"},
    {"code": "292081", "title": "Opticians, Dispensing"},
    {"code": "292091", "title": "Orthotists and Prosthetists"},
    {"code": "292092", "title": "Hearing Aid Specialists"},
    {"code": "292098", "title": "Health Information Technologists and Medical Registrars"},
    {"code": "292099", "title": "Health Technologists and Technicians, All Other"},
    {"code": "299091", "title": "Athletic Trainers"},
    {"code": "299092", "title": "Genetic Counselors"},
    {"code": "299093", "title": "Surgical Assistants"},
    {"code": "299099", "title": "Healthcare Practitioners and Technical Workers, All Other"},

    # 31 - Healthcare Support Occupations
    {"code": "311011", "title": "Home Health Aides"},
    {"code": "311120", "title": "Personal Care Aides"},
    {"code": "311131", "title": "Nursing Assistants"},
    {"code": "311132", "title": "Orderlies"},
    {"code": "311133", "title": "Psychiatric Aides"},
    {"code": "312011", "title": "Occupational Therapy Assistants"},
    {"code": "312021", "title": "Physical Therapist Assistants"},
    {"code": "319011", "title": "Massage Therapists"},
    {"code": "319091", "title": "Dental Assistants"},
    {"code": "319092", "title": "Medical Assistants"},
    {"code": "319093", "title": "Medical Equipment Preparers"},
    {"code": "319094", "title": "Medical Transcriptionists"},
    {"code": "319095", "title": "Pharmacy Aides"},
    {"code": "319096", "title": "Veterinary Assistants and Laboratory Animal Caretakers"},
    {"code": "319097", "title": "Phlebotomists"},
    {"code": "319099", "title": "Healthcare Support Workers, All Other"},

    # 33 - Protective Service Occupations
    {"code": "331011", "title": "First-Line Supervisors of Correctional Officers"},
    {"code": "331012", "title": "First-Line Supervisors of Police and Detectives"},
    {"code": "331021", "title": "First-Line Supervisors of Firefighting and Prevention Workers"},
    {"code": "331091", "title": "First-Line Supervisors of Security Workers"},
    {"code": "331099", "title": "First-Line Supervisors of Protective Service Workers, All Other"},
    {"code": "332011", "title": "Firefighters"},
    {"code": "332021", "title": "Fire Inspectors and Investigators"},
    {"code": "332022", "title": "Forest Fire Inspectors and Prevention Specialists"},
    {"code": "333011", "title": "Bailiffs"},
    {"code": "333012", "title": "Correctional Officers and Jailers"},
    {"code": "333021", "title": "Detectives and Criminal Investigators"},
    {"code": "333041", "title": "Parking Enforcement Workers"},
    {"code": "333051", "title": "Police and Sheriff's Patrol Officers"},
    {"code": "333052", "title": "Transit and Railroad Police"},
    {"code": "339011", "title": "Animal Control Workers"},
    {"code": "339021", "title": "Private Detectives and Investigators"},
    {"code": "339030", "title": "Security Guards and Gambling Surveillance Officers"},
    {"code": "339091", "title": "Crossing Guards and Flaggers"},
    {"code": "339093", "title": "Transportation Security Screeners"},
    {"code": "339094", "title": "School Bus Monitors"},
    {"code": "339099", "title": "Protective Service Workers, All Other"},

    # 35 - Food Preparation and Serving Related Occupations
    {"code": "351011", "title": "Chefs and Head Cooks"},
    {"code": "351012", "title": "First-Line Supervisors of Food Preparation and Serving Workers"},
    {"code": "352011", "title": "Cooks, Fast Food"},
    {"code": "352012", "title": "Cooks, Institution and Cafeteria"},
    {"code": "352013", "title": "Cooks, Private Household"},
    {"code": "352014", "title": "Cooks, Restaurant"},
    {"code": "352015", "title": "Cooks, Short Order"},
    {"code": "352019", "title": "Cooks, All Other"},
    {"code": "352021", "title": "Food Preparation Workers"},
    {"code": "353011", "title": "Bartenders"},
    {"code": "353023", "title": "Fast Food and Counter Workers"},
    {"code": "353031", "title": "Waiters and Waitresses"},
    {"code": "353041", "title": "Food Servers, Nonrestaurant"},
    {"code": "359011", "title": "Dining Room and Cafeteria Attendants and Bartender Helpers"},
    {"code": "359021", "title": "Dishwashers"},
    {"code": "359031", "title": "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop"},
    {"code": "359099", "title": "Food Preparation and Serving Related Workers, All Other"},

    # 37 - Building and Grounds Cleaning and Maintenance Occupations
    {"code": "371011", "title": "First-Line Supervisors of Housekeeping and Janitorial Workers"},
    {"code": "371012", "title": "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers"},
    {"code": "372011", "title": "Janitors and Cleaners, Except Maids and Housekeeping Cleaners"},
    {"code": "372012", "title": "Maids and Housekeeping Cleaners"},
    {"code": "372019", "title": "Building Cleaning Workers, All Other"},
    {"code": "372021", "title": "Pest Control Workers"},
    {"code": "373011", "title": "Landscaping and Groundskeeping Workers"},
    {"code": "373012", "title": "Pesticide Handlers, Sprayers, and Applicators, Vegetation"},
    {"code": "373013", "title": "Tree Trimmers and Pruners"},
    {"code": "373019", "title": "Grounds Maintenance Workers, All Other"},

    # 39 - Personal Care and Service Occupations
    {"code": "391010", "title": "First-Line Supervisors of Personal Service and Entertainment and Recreation Workers"},
    {"code": "391021", "title": "First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services"},
    {"code": "391022", "title": "First-Line Supervisors of Personal Service Workers"},
    {"code": "392011", "title": "Animal Trainers"},
    {"code": "392021", "title": "Animal Caretakers"},
    {"code": "393012", "title": "Gambling and Sports Book Writers and Runners"},
    {"code": "393019", "title": "Gambling Service Workers, All Other"},
    {"code": "393021", "title": "Motion Picture Projectionists"},
    {"code": "393031", "title": "Ushers, Lobby Attendants, and Ticket Takers"},
    {"code": "393091", "title": "Amusement and Recreation Attendants"},
    {"code": "393093", "title": "Locker Room, Coatroom, and Dressing Room Attendants"},
    {"code": "393099", "title": "Entertainment Attendants and Related Workers, All Other"},
    {"code": "394031", "title": "Morticians, Undertakers, and Funeral Arrangers"},
    {"code": "395011", "title": "Barbers"},
    {"code": "395012", "title": "Hairdressers, Hairstylists, and Cosmetologists"},
    {"code": "395091", "title": "Makeup Artists, Theatrical and Performance"},
    {"code": "395092", "title": "Manicurists and Pedicurists"},
    {"code": "395093", "title": "Shampooers"},
    {"code": "395094", "title": "Skincare Specialists"},
    {"code": "396011", "title": "Baggage Porters and Bellhops"},
    {"code": "396012", "title": "Concierges"},
    {"code": "397010", "title": "Tour and Travel Guides"},
    {"code": "399011", "title": "Childcare Workers"},
    {"code": "399031", "title": "Exercise Trainers and Group Fitness Instructors"},
    {"code": "399032", "title": "Recreation Workers"},
    {"code": "399041", "title": "Residential Advisors"},
    {"code": "399099", "title": "Personal Care and Service Workers, All Other"},

    # 41 - Sales and Related Occupations
    {"code": "411011", "title": "First-Line Supervisors of Retail Sales Workers"},
    {"code": "411012", "title": "First-Line Supervisors of Non-Retail Sales Workers"},
    {"code": "412011", "title": "Cashiers"},
    {"code": "412012", "title": "Gambling Change Persons and Booth Cashiers"},
    {"code": "412021", "title": "Counter and Rental Clerks"},
    {"code": "412022", "title": "Parts Salespersons"},
    {"code": "412031", "title": "Retail Salespersons"},
    {"code": "413011", "title": "Advertising Sales Agents"},
    {"code": "413021", "title": "Insurance Sales Agents"},
    {"code": "413031", "title": "Securities, Commodities, and Financial Services Sales Agents"},
    {"code": "413041", "title": "Travel Agents"},
    {"code": "413091", "title": "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel"},
    {"code": "414011", "title": "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products"},
    {"code": "414012", "title": "Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products"},
    {"code": "419011", "title": "Demonstrators and Product Promoters"},
    {"code": "419021", "title": "Real Estate Brokers"},
    {"code": "419022", "title": "Real Estate Sales Agents"},
    {"code": "419031", "title": "Sales Engineers"},
    {"code": "419041", "title": "Telemarketers"},
    {"code": "419091", "title": "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers"},
    {"code": "419099", "title": "Sales and Related Workers, All Other"},

    # 43 - Office and Administrative Support Occupations
    {"code": "431011", "title": "First-Line Supervisors of Office and Administrative Support Workers"},
    {"code": "432011", "title": "Switchboard Operators, Including Answering Service"},
    {"code": "432021", "title": "Telephone Operators"},
    {"code": "432099", "title": "Communications Equipment Operators, All Other"},
    {"code": "433011", "title": "Bill and Account Collectors"},
    {"code": "433021", "title": "Billing and Posting Clerks"},
    {"code": "433031", "title": "Bookkeeping, Accounting, and Auditing Clerks"},
    {"code": "433041", "title": "Gaming Cage Workers"},
    {"code": "433051", "title": "Payroll and Timekeeping Clerks"},
    {"code": "433061", "title": "Procurement Clerks"},
    {"code": "433071", "title": "Tellers"},
    {"code": "433099", "title": "Financial Clerks, All Other"},
    {"code": "434011", "title": "Brokerage Clerks"},
    {"code": "434021", "title": "Correspondence Clerks"},
    {"code": "434031", "title": "Court, Municipal, and License Clerks"},
    {"code": "434041", "title": "Credit Authorizers, Checkers, and Clerks"},
    {"code": "434051", "title": "Customer Service Representatives"},
    {"code": "434061", "title": "Eligibility Interviewers, Government Programs"},
    {"code": "434071", "title": "File Clerks"},
    {"code": "434081", "title": "Hotel, Motel, and Resort Desk Clerks"},
    {"code": "434111", "title": "Interviewers, Except Eligibility and Loan"},
    {"code": "434121", "title": "Library Assistants, Clerical"},
    {"code": "434131", "title": "Loan Interviewers and Clerks"},
    {"code": "434141", "title": "New Accounts Clerks"},
    {"code": "434151", "title": "Order Clerks"},
    {"code": "434161", "title": "Human Resources Assistants, Except Payroll and Timekeeping"},
    {"code": "434171", "title": "Receptionists and Information Clerks"},
    {"code": "434181", "title": "Reservation and Transportation Ticket Agents and Travel Clerks"},
    {"code": "434199", "title": "Information and Record Clerks, All Other"},
    {"code": "435011", "title": "Cargo and Freight Agents"},
    {"code": "435021", "title": "Couriers and Messengers"},
    {"code": "435031", "title": "Public Safety Telecommunicators"},
    {"code": "435032", "title": "Dispatchers, Except Police, Fire, and Ambulance"},
    {"code": "435041", "title": "Meter Readers, Utilities"},
    {"code": "435051", "title": "Postal Service Clerks"},
    {"code": "435052", "title": "Postal Service Mail Carriers"},
    {"code": "435053", "title": "Postal Service Mail Sorters, Processors, and Processing Machine Operators"},
    {"code": "435061", "title": "Production, Planning, and Expediting Clerks"},
    {"code": "435071", "title": "Shipping, Receiving, and Inventory Clerks"},
    {"code": "435111", "title": "Weighers, Measurers, Checkers, and Samplers, Recordkeeping"},
    {"code": "436011", "title": "Executive Secretaries and Executive Administrative Assistants"},
    {"code": "436012", "title": "Legal Secretaries and Administrative Assistants"},
    {"code": "436013", "title": "Medical Secretaries and Administrative Assistants"},
    {"code": "436014", "title": "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive"},
    {"code": "439011", "title": "Computer Operators"},
    {"code": "439021", "title": "Data Entry Keyers"},
    {"code": "439022", "title": "Word Processors and Typists"},
    {"code": "439041", "title": "Insurance Claims and Policy Processing Clerks"},
    {"code": "439051", "title": "Mail Clerks and Mail Machine Operators, Except Postal Service"},
    {"code": "439061", "title": "Office Clerks, General"},
    {"code": "439071", "title": "Office Machine Operators, Except Computer"},
    {"code": "439081", "title": "Proofreaders and Copy Markers"},
    {"code": "439111", "title": "Statistical Assistants"},
    {"code": "439199", "title": "Office and Administrative Support Workers, All Other"},

    # 45 - Farming, Fishing, and Forestry Occupations
    {"code": "451011", "title": "First-Line Supervisors of Farming, Fishing, and Forestry Workers"},
    {"code": "452011", "title": "Agricultural Inspectors"},
    {"code": "452041", "title": "Graders and Sorters, Agricultural Products"},
    {"code": "452091", "title": "Agricultural Equipment Operators"},
    {"code": "452092", "title": "Farmworkers and Laborers, Crop, Nursery, and Greenhouse"},
    {"code": "452093", "title": "Farmworkers, Farm, Ranch, and Aquacultural Animals"},
    {"code": "452099", "title": "Agricultural Workers, All Other"},
    {"code": "453031", "title": "Fishing and Hunting Workers"},
    {"code": "454011", "title": "Forest and Conservation Workers"},
    {"code": "454022", "title": "Logging Equipment Operators"},
    {"code": "454023", "title": "Log Graders and Scalers"},
    {"code": "454029", "title": "Logging Workers, All Other"},

    # 47 - Construction and Extraction Occupations
    {"code": "471011", "title": "First-Line Supervisors of Construction Trades and Extraction Workers"},
    {"code": "472011", "title": "Boilermakers"},
    {"code": "472021", "title": "Brickmasons and Blockmasons"},
    {"code": "472022", "title": "Stonemasons"},
    {"code": "472031", "title": "Carpenters"},
    {"code": "472041", "title": "Carpet Installers"},
    {"code": "472042", "title": "Floor Layers, Except Carpet, Wood, and Hard Tiles"},
    {"code": "472043", "title": "Floor Sanders and Finishers"},
    {"code": "472044", "title": "Tile and Stone Setters"},
    {"code": "472051", "title": "Cement Masons and Concrete Finishers"},
    {"code": "472053", "title": "Terrazzo Workers and Finishers"},
    {"code": "472061", "title": "Construction Laborers"},
    {"code": "472071", "title": "Paving, Surfacing, and Tamping Equipment Operators"},
    {"code": "472072", "title": "Pile Driver Operators"},
    {"code": "472073", "title": "Operating Engineers and Other Construction Equipment Operators"},
    {"code": "472081", "title": "Drywall and Ceiling Tile Installers"},
    {"code": "472082", "title": "Tapers"},
    {"code": "472111", "title": "Electricians"},
    {"code": "472121", "title": "Glaziers"},
    {"code": "472131", "title": "Insulation Workers, Floor, Ceiling, and Wall"},
    {"code": "472132", "title": "Insulation Workers, Mechanical"},
    {"code": "472141", "title": "Painters, Construction and Maintenance"},
    {"code": "472142", "title": "Paperhangers"},
    {"code": "472151", "title": "Pipelayers"},
    {"code": "472152", "title": "Plumbers, Pipefitters, and Steamfitters"},
    {"code": "472161", "title": "Plasterers and Stucco Masons"},
    {"code": "472171", "title": "Reinforcing Iron and Rebar Workers"},
    {"code": "472181", "title": "Roofers"},
    {"code": "472211", "title": "Sheet Metal Workers"},
    {"code": "472221", "title": "Structural Iron and Steel Workers"},
    {"code": "472231", "title": "Solar Photovoltaic Installers"},
    {"code": "473011", "title": "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters"},
    {"code": "473012", "title": "Helpers--Carpenters"},
    {"code": "473013", "title": "Helpers--Electricians"},
    {"code": "473014", "title": "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons"},
    {"code": "473015", "title": "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters"},
    {"code": "473016", "title": "Helpers--Roofers"},
    {"code": "473019", "title": "Helpers, Construction Trades, All Other"},
    {"code": "474011", "title": "Construction and Building Inspectors"},
    {"code": "474021", "title": "Elevator and Escalator Installers and Repairers"},
    {"code": "474031", "title": "Fence Erectors"},
    {"code": "474041", "title": "Hazardous Materials Removal Workers"},
    {"code": "474051", "title": "Highway Maintenance Workers"},
    {"code": "474061", "title": "Rail-Track Laying and Maintenance Equipment Operators"},
    {"code": "474071", "title": "Septic Tank Servicers and Sewer Pipe Cleaners"},
    {"code": "474090", "title": "Miscellaneous Construction and Related Workers"},
    {"code": "475010", "title": "Derrick, Rotary Drill, and Service Unit Operators, Oil and Gas"},
    {"code": "475012", "title": "Rotary Drill Operators, Oil and Gas"},
    {"code": "475013", "title": "Service Unit Operators, Oil and Gas"},
    {"code": "475021", "title": "Earth Drillers, Except Oil and Gas"},
    {"code": "475022", "title": "Excavating and Loading Machine and Dragline Operators, Surface Mining"},
    {"code": "475031", "title": "Explosives Workers, Ordnance Handling Experts, and Blasters"},
    {"code": "475032", "title": "Continuous Mining Machine Operators"},
    {"code": "475040", "title": "Mining Machine Operators"},
    {"code": "475051", "title": "Rock Splitters, Quarry"},
    {"code": "475061", "title": "Roof Bolters, Mining"},
    {"code": "475071", "title": "Roustabouts, Oil and Gas"},
    {"code": "475081", "title": "Helpers--Extraction Workers"},
    {"code": "475099", "title": "Extraction Workers, All Other"},

    # 49 - Installation, Maintenance, and Repair Occupations
    {"code": "491011", "title": "First-Line Supervisors of Mechanics, Installers, and Repairers"},
    {"code": "492011", "title": "Computer, Automated Teller, and Office Machine Repairers"},
    {"code": "492021", "title": "Radio, Cellular, and Tower Equipment Installers and Repairers"},
    {"code": "492022", "title": "Telecommunications Equipment Installers and Repairers, Except Line Installers"},
    {"code": "492091", "title": "Avionics Technicians"},
    {"code": "492092", "title": "Electric Motor, Power Tool, and Related Repairers"},
    {"code": "492093", "title": "Electrical and Electronics Installers and Repairers, Transportation Equipment"},
    {"code": "492094", "title": "Electrical and Electronics Repairers, Commercial and Industrial Equipment"},
    {"code": "492095", "title": "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay"},
    {"code": "492096", "title": "Electronic Equipment Installers and Repairers, Motor Vehicles"},
    {"code": "492097", "title": "Audiovisual Equipment Installers and Repairers"},
    {"code": "492098", "title": "Security and Fire Alarm Systems Installers"},
    {"code": "493011", "title": "Aircraft Mechanics and Service Technicians"},
    {"code": "493021", "title": "Automotive Body and Related Repairers"},
    {"code": "493022", "title": "Automotive Glass Installers and Repairers"},
    {"code": "493023", "title": "Automotive Service Technicians and Mechanics"},
    {"code": "493031", "title": "Bus and Truck Mechanics and Diesel Engine Specialists"},
    {"code": "493040", "title": "Heavy Vehicle and Mobile Equipment Service Technicians"},
    {"code": "493041", "title": "Farm Equipment Mechanics and Service Technicians"},
    {"code": "493042", "title": "Mobile Heavy Equipment Mechanics, Except Engines"},
    {"code": "493043", "title": "Rail Car Repairers"},
    {"code": "493051", "title": "Motorboat Mechanics and Service Technicians"},
    {"code": "493052", "title": "Motorcycle Mechanics"},
    {"code": "493053", "title": "Outdoor Power Equipment and Other Small Engine Mechanics"},
    {"code": "493091", "title": "Bicycle Repairers"},
    {"code": "493092", "title": "Recreational Vehicle Service Technicians"},
    {"code": "493093", "title": "Tire Repairers and Changers"},
    {"code": "499011", "title": "Mechanical Door Repairers"},
    {"code": "499012", "title": "Control and Valve Installers and Repairers, Except Mechanical Door"},
    {"code": "499021", "title": "Heating, Air Conditioning, and Refrigeration Mechanics and Installers"},
    {"code": "499031", "title": "Home Appliance Repairers"},
    {"code": "499041", "title": "Industrial Machinery Mechanics"},
    {"code": "499043", "title": "Maintenance Workers, Machinery"},
    {"code": "499044", "title": "Millwrights"},
    {"code": "499045", "title": "Refractory Materials Repairers, Except Brickmasons"},
    {"code": "499051", "title": "Electrical Power-Line Installers and Repairers"},
    {"code": "499052", "title": "Telecommunications Line Installers and Repairers"},
    {"code": "499061", "title": "Camera and Photographic Equipment Repairers"},
    {"code": "499062", "title": "Medical Equipment Repairers"},
    {"code": "499063", "title": "Musical Instrument Tuners and Repairers"},
    {"code": "499064", "title": "Watch and Clock Repairers"},
    {"code": "499069", "title": "Precision Instrument and Equipment Repairers, All Other"},
    {"code": "499071", "title": "Maintenance and Repair Workers, General"},
    {"code": "499081", "title": "Wind Turbine Service Technicians"},
    {"code": "499091", "title": "Coin, Vending, and Amusement Machine Servicers and Repairers"},
    {"code": "499094", "title": "Locksmiths and Safe Repairers"},
    {"code": "499095", "title": "Manufactured Building and Mobile Home Installers"},
    {"code": "499096", "title": "Riggers"},
    {"code": "499097", "title": "Signal and Track Switch Repairers"},
    {"code": "499098", "title": "Helpers--Installation, Maintenance, and Repair Workers"},
    {"code": "499099", "title": "Installation, Maintenance, and Repair Workers, All Other"},

    # 51 - Production Occupations
    {"code": "511011", "title": "First-Line Supervisors of Production and Operating Workers"},
    {"code": "512011", "title": "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers"},
    {"code": "512021", "title": "Coil Winders, Tapers, and Finishers"},
    {"code": "512023", "title": "Electromechanical Equipment Assemblers"},
    {"code": "512028", "title": "Electrical, Electronic, and Electromechanical Assemblers, Except Coil Winders, Tapers, and Finishers"},
    {"code": "512031", "title": "Engine and Other Machine Assemblers"},
    {"code": "512041", "title": "Structural Metal Fabricators and Fitters"},
    {"code": "512051", "title": "Fiberglass Laminators and Fabricators"},
    {"code": "512061", "title": "Timing Device Assemblers and Adjusters"},
    {"code": "512091", "title": "Fiberglass Laminators and Fabricators"},
    {"code": "512098", "title": "Miscellaneous Assemblers and Fabricators"},
    {"code": "513011", "title": "Bakers"},
    {"code": "513021", "title": "Butchers and Meat Cutters"},
    {"code": "513022", "title": "Meat, Poultry, and Fish Cutters and Trimmers"},
    {"code": "513023", "title": "Slaughterers and Meat Packers"},
    {"code": "513091", "title": "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders"},
    {"code": "513092", "title": "Food Batchmakers"},
    {"code": "513093", "title": "Food Cooking Machine Operators and Tenders"},
    {"code": "513099", "title": "Food Processing Workers, All Other"},
    {"code": "514011", "title": "Computer Numerically Controlled Tool Operators"},
    {"code": "514012", "title": "Computer Numerically Controlled Tool Programmers"},
    {"code": "514021", "title": "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514022", "title": "Forging Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514023", "title": "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514031", "title": "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514032", "title": "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514033", "title": "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514034", "title": "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514035", "title": "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514041", "title": "Machinists"},
    {"code": "514051", "title": "Metal-Refining Furnace Operators and Tenders"},
    {"code": "514052", "title": "Pourers and Casters, Metal"},
    {"code": "514061", "title": "Model Makers, Metal and Plastic"},
    {"code": "514062", "title": "Patternmakers, Metal and Plastic"},
    {"code": "514071", "title": "Foundry Mold and Coremakers"},
    {"code": "514072", "title": "Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514081", "title": "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514111", "title": "Tool and Die Makers"},
    {"code": "514121", "title": "Welders, Cutters, Solderers, and Brazers"},
    {"code": "514122", "title": "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders"},
    {"code": "514191", "title": "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514192", "title": "Layout Workers, Metal and Plastic"},
    {"code": "514193", "title": "Plating Machine Setters, Operators, and Tenders, Metal and Plastic"},
    {"code": "514194", "title": "Tool Grinders, Filers, and Sharpeners"},
    {"code": "514199", "title": "Metal Workers and Plastic Workers, All Other"},
    {"code": "515111", "title": "Prepress Technicians and Workers"},
    {"code": "515112", "title": "Printing Press Operators"},
    {"code": "515113", "title": "Print Binding and Finishing Workers"},
    {"code": "516011", "title": "Laundry and Dry-Cleaning Workers"},
    {"code": "516021", "title": "Pressers, Textile, Garment, and Related Materials"},
    {"code": "516031", "title": "Sewing Machine Operators"},
    {"code": "516041", "title": "Shoe and Leather Workers and Repairers"},
    {"code": "516042", "title": "Shoe Machine Operators and Tenders"},
    {"code": "516051", "title": "Sewers, Hand"},
    {"code": "516052", "title": "Tailors, Dressmakers, and Custom Sewers"},
    {"code": "516061", "title": "Textile Bleaching and Dyeing Machine Operators and Tenders"},
    {"code": "516062", "title": "Textile Cutting Machine Setters, Operators, and Tenders"},
    {"code": "516063", "title": "Textile Knitting and Weaving Machine Setters, Operators, and Tenders"},
    {"code": "516064", "title": "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders"},
    {"code": "516091", "title": "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers"},
    {"code": "516092", "title": "Fabric and Apparel Patternmakers"},
    {"code": "516093", "title": "Upholsterers"},
    {"code": "516099", "title": "Textile, Apparel, and Furnishings Workers, All Other"},
    {"code": "517011", "title": "Cabinetmakers and Bench Carpenters"},
    {"code": "517021", "title": "Furniture Finishers"},
    {"code": "517031", "title": "Model Makers, Wood"},
    {"code": "517032", "title": "Patternmakers, Wood"},
    {"code": "517041", "title": "Sawing Machine Setters, Operators, and Tenders, Wood"},
    {"code": "517042", "title": "Woodworking Machine Setters, Operators, and Tenders, Except Sawing"},
    {"code": "517099", "title": "Woodworkers, All Other"},
    {"code": "518011", "title": "Nuclear Power Reactor Operators"},
    {"code": "518012", "title": "Power Distributors and Dispatchers"},
    {"code": "518013", "title": "Power Plant Operators"},
    {"code": "518021", "title": "Stationary Engineers and Boiler Operators"},
    {"code": "518031", "title": "Water and Wastewater Treatment Plant and System Operators"},
    {"code": "518091", "title": "Chemical Plant and System Operators"},
    {"code": "518092", "title": "Gas Plant Operators"},
    {"code": "518093", "title": "Petroleum Pump System Operators, Refinery Operators, and Gaugers"},
    {"code": "518099", "title": "Plant and System Operators, All Other"},
    {"code": "519011", "title": "Chemical Equipment Operators and Tenders"},
    {"code": "519012", "title": "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders"},
    {"code": "519021", "title": "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders"},
    {"code": "519022", "title": "Grinding and Polishing Workers, Hand"},
    {"code": "519023", "title": "Mixing and Blending Machine Setters, Operators, and Tenders"},
    {"code": "519031", "title": "Cutters and Trimmers, Hand"},
    {"code": "519032", "title": "Cutting and Slicing Machine Setters, Operators, and Tenders"},
    {"code": "519041", "title": "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders"},
    {"code": "519051", "title": "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders"},
    {"code": "519061", "title": "Inspectors, Testers, Sorters, Samplers, and Weighers"},
    {"code": "519071", "title": "Jewelers and Precious Stone and Metal Workers"},
    {"code": "519081", "title": "Dental Laboratory Technicians"},
    {"code": "519082", "title": "Medical Appliance Technicians"},
    {"code": "519083", "title": "Ophthalmic Laboratory Technicians"},
    {"code": "519111", "title": "Packaging and Filling Machine Operators and Tenders"},
    {"code": "519121", "title": "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders"},
    {"code": "519122", "title": "Painters, Transportation Equipment"},
    {"code": "519123", "title": "Painting, Coating, and Decorating Workers"},
    {"code": "519141", "title": "Semiconductor Processing Technicians"},
    {"code": "519151", "title": "Photographic Process Workers and Processing Machine Operators"},
    {"code": "519161", "title": "Computer Numerically Controlled Tool Operators"},
    {"code": "519191", "title": "Adhesive Bonding Machine Operators and Tenders"},
    {"code": "519192", "title": "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders"},
    {"code": "519193", "title": "Cooling and Freezing Equipment Operators and Tenders"},
    {"code": "519194", "title": "Etchers and Engravers"},
    {"code": "519195", "title": "Molders, Shapers, and Casters, Except Metal and Plastic"},
    {"code": "519196", "title": "Paper Goods Machine Setters, Operators, and Tenders"},
    {"code": "519197", "title": "Tire Builders"},
    {"code": "519198", "title": "Helpers--Production Workers"},
    {"code": "519199", "title": "Production Workers, All Other"},

    # 53 - Transportation and Material Moving Occupations
    {"code": "531000", "title": "Supervisors of Transportation and Material Moving Workers"},
    {"code": "531042", "title": "First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand"},
    {"code": "531043", "title": "First-Line Supervisors of Material-Moving Machine and Vehicle Operators"},
    {"code": "531044", "title": "First-Line Supervisors of Passenger Attendants"},
    {"code": "531047", "title": "First-Line Supervisors of Transportation Workers, All Other"},
    {"code": "532011", "title": "Airline Pilots, Copilots, and Flight Engineers"},
    {"code": "532012", "title": "Commercial Pilots"},
    {"code": "532021", "title": "Air Traffic Controllers"},
    {"code": "532022", "title": "Airfield Operations Specialists"},
    {"code": "532031", "title": "Flight Attendants"},
    {"code": "533011", "title": "Ambulance Drivers and Attendants, Except Emergency Medical Technicians"},
    {"code": "533031", "title": "Driver/Sales Workers"},
    {"code": "533032", "title": "Heavy and Tractor-Trailer Truck Drivers"},
    {"code": "533033", "title": "Light Truck Drivers"},
    {"code": "533041", "title": "Taxi Drivers"},
    {"code": "533051", "title": "Bus Drivers, School"},
    {"code": "533052", "title": "Bus Drivers, Transit and Intercity"},
    {"code": "533053", "title": "Shuttle Drivers and Chauffeurs"},
    {"code": "533054", "title": "Passenger Vehicle Drivers, Except Bus Drivers, Transit and Intercity"},
    {"code": "533099", "title": "Motor Vehicle Operators, All Other"},
    {"code": "534011", "title": "Locomotive Engineers"},
    {"code": "534013", "title": "Rail Yard Engineers, Dinkey Operators, and Hostlers"},
    {"code": "534021", "title": "Railroad Brake, Signal, and Switch Operators and Locomotive Firers"},
    {"code": "534022", "title": "Railroad Conductors and Yardmasters"},
    {"code": "534031", "title": "Subway and Streetcar Operators"},
    {"code": "534041", "title": "Subway and Streetcar Operators"},
    {"code": "534099", "title": "Rail Transportation Workers, All Other"},
    {"code": "535011", "title": "Sailors and Marine Oilers"},
    {"code": "535021", "title": "Captains, Mates, and Pilots of Water Vessels"},
    {"code": "535022", "title": "Motorboat Operators"},
    {"code": "535031", "title": "Ship Engineers"},
    {"code": "536011", "title": "Bridge and Lock Tenders"},
    {"code": "536021", "title": "Parking Attendants"},
    {"code": "536031", "title": "Automotive and Watercraft Service Attendants"},
    {"code": "536041", "title": "Traffic Technicians"},
    {"code": "536051", "title": "Transportation Inspectors"},
    {"code": "536061", "title": "Passenger Attendants"},
    {"code": "536099", "title": "Transportation Workers, All Other"},
    {"code": "537011", "title": "Conveyor Operators and Tenders"},
    {"code": "537021", "title": "Crane and Tower Operators"},
    {"code": "537031", "title": "Dredge Operators"},
    {"code": "537032", "title": "Excavating and Loading Machine and Dragline Operators"},
    {"code": "537041", "title": "Hoist and Winch Operators"},
    {"code": "537051", "title": "Industrial Truck and Tractor Operators"},
    {"code": "537061", "title": "Cleaners of Vehicles and Equipment"},
    {"code": "537062", "title": "Laborers and Freight, Stock, and Material Movers, Hand"},
    {"code": "537063", "title": "Machine Feeders and Offbearers"},
    {"code": "537064", "title": "Packers and Packagers, Hand"},
    {"code": "537065", "title": "Stockers and Order Fillers"},
    {"code": "537072", "title": "Pump Operators, Except Wellhead Pumpers"},
    {"code": "537073", "title": "Wellhead Pumpers"},
    {"code": "537081", "title": "Refuse and Recyclable Material Collectors"},
    {"code": "537111", "title": "Mine Shuttle Car Operators"},
    {"code": "537121", "title": "Tank Car, Truck, and Ship Loaders"},
    {"code": "537199", "title": "Material Moving Workers, All Other"},
]


def get_occupation_list() -> List[SOCOccupation]:
    """
    Get the full list of SOC occupations with major group information.

    Returns:
        List of SOCOccupation objects
    """
    result = []
    for occ in SOC_OCCUPATIONS:
        major_group = occ["code"][:2]
        result.append(SOCOccupation(
            code=occ["code"],
            title=occ["title"],
            major_group=major_group,
            major_group_title=MAJOR_GROUPS.get(major_group, "Unknown"),
        ))
    return result


def search_occupations(query: str, limit: int = 20) -> List[SOCOccupation]:
    """
    Search occupations by title or code.

    Args:
        query: Search string (matches title or SOC code)
        limit: Maximum results to return

    Returns:
        List of matching SOCOccupation objects
    """
    query_lower = query.lower().strip()

    if not query_lower:
        return []

    results = []

    for occ in SOC_OCCUPATIONS:
        # Match by code or title
        if (query_lower in occ["code"] or
            query_lower in occ["title"].lower()):
            major_group = occ["code"][:2]
            results.append(SOCOccupation(
                code=occ["code"],
                title=occ["title"],
                major_group=major_group,
                major_group_title=MAJOR_GROUPS.get(major_group, "Unknown"),
            ))

            if len(results) >= limit:
                break

    return results


def get_occupation_by_code(code: str) -> Optional[SOCOccupation]:
    """
    Get a specific occupation by its SOC code.

    Args:
        code: 6-digit SOC code (with or without hyphen)

    Returns:
        SOCOccupation or None if not found
    """
    code_clean = code.replace("-", "").strip()

    for occ in SOC_OCCUPATIONS:
        if occ["code"] == code_clean:
            major_group = occ["code"][:2]
            return SOCOccupation(
                code=occ["code"],
                title=occ["title"],
                major_group=major_group,
                major_group_title=MAJOR_GROUPS.get(major_group, "Unknown"),
            )

    return None


def get_major_groups() -> Dict[str, str]:
    """Get dictionary of major occupation groups."""
    return MAJOR_GROUPS
